backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "/assets/media"

collections:
  - name: "topic" # Used in routes, e.g., /admin/collections/blog
    label: "Topic" # Used in the UI
    folder: "data/topics" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "topic"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

      